# 基本は github.com のレポジトリを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

#ステータスラインのテーマ
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

#ステータスラインのテーマ
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# change colorscheme for each buffer
[[plugins]]
repo = 'caglartoklu/ftcolor.vim'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'keith/swift.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

#vimfilerを使うために必要
[[plugins]]
repo =  'Shougo/unite.vim'

#ディレクトリ表示
[[plugins]]
repo = 'Shougo/vimfiler'

# 行末スペースを赤く表示
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# GBlameなど
# [[plugins]]
# repo = 'tpope/vim-fugitive'
# [[plugins]]
# repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'vim-scripts/applescript.vim'

[[plugins]]
repo = 'ethereum/vim-solidity'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'

[[plugins]]
repo = 'udalov/kotlin-vim'
